### ISSUE TITLE
Amongus mancanti

### ISSUE THREAD

**Issue by alessandro-massarenti** [AmongTOS/Assignment-3#1]
Non vedo amonghi nella pagina 1,5,13,15,16 del file  [Pdf](https://github.com/AmongTOS/MTSS-Assignment-3/blob/main/MTSS%20Assignment%203.pdf).

Questo è palesemente un **bug**

**Comment by AlecsFerra** [comment]
Ho troppo swag per queste cose.

**Comment by AlecsFerra** [comment]
Comunque in pagina 5 c'è
